import type { Metadata } from "next";
import "../sass/style.scss";
import StoreProvider from "@/Redux/StoreProvider";
import ModalsInit from "@/Modals/ModalsInit";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <StoreProvider>
            <html lang="en">
                <body>
                    <div className="__MAIN_SITE__">{children}</div>
                    <ModalsInit />
                </body>
            </html>
        </StoreProvider>
    );
}
